
import __ASTRO_IMAGE_IMPORT_1reFJn from "../avatar.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Faddendum%2Findex.ar.md";
import __ASTRO_IMAGE_IMPORT_1ruqtC from "../avatar.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Faddendum%2Findex.en.md";
import __ASTRO_IMAGE_IMPORT_1rLuhD from "../avatar.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Faddendum%2Findex.it.md";
import __ASTRO_IMAGE_IMPORT_1sS5sO from "../avatar.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Faddendum%2Findex.zh.md";
import __ASTRO_IMAGE_IMPORT_DOR21 from "../flopp2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fhome%2Findex.ar.md";
import __ASTRO_IMAGE_IMPORT_E5BLg from "../flopp2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fhome%2Findex.en.md";
import __ASTRO_IMAGE_IMPORT_EmFzh from "../flopp2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fhome%2Findex.it.md";
import __ASTRO_IMAGE_IMPORT_FtgKs from "../flopp2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fhome%2Findex.zh.md";
import __ASTRO_IMAGE_IMPORT_Z2lmA0V from "./PixelatedGreenTreeSide.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fshowing-off-blog-features%2Findex.en.md";
import __ASTRO_IMAGE_IMPORT_1mBTjN from "./cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fshowing-off-blog-features%2Findex.en.md";
import __ASTRO_IMAGE_IMPORT_Z2l5wcU from "./PixelatedGreenTreeSide.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fshowing-off-blog-features%2Findex.it.md";
import __ASTRO_IMAGE_IMPORT_1mSX7O from "./cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fshowing-off-blog-features%2Findex.it.md";
import __ASTRO_IMAGE_IMPORT_Z2lCkKb from "./PixelatedGreenTreeSide.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fshowing-off-blog-features%2Findex.ar.md";
import __ASTRO_IMAGE_IMPORT_1mm9zy from "./cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fshowing-off-blog-features%2Findex.ar.md";
import __ASTRO_IMAGE_IMPORT_Z2jXV1J from "./PixelatedGreenTreeSide.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fshowing-off-blog-features%2Findex.zh.md";
import __ASTRO_IMAGE_IMPORT_1o0yj0 from "./cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fshowing-off-blog-features%2Findex.zh.md";
export default new Map([["../avatar.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Faddendum%2Findex.ar.md", __ASTRO_IMAGE_IMPORT_1reFJn], ["../avatar.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Faddendum%2Findex.en.md", __ASTRO_IMAGE_IMPORT_1ruqtC], ["../avatar.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Faddendum%2Findex.it.md", __ASTRO_IMAGE_IMPORT_1rLuhD], ["../avatar.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Faddendum%2Findex.zh.md", __ASTRO_IMAGE_IMPORT_1sS5sO], ["../flopp2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fhome%2Findex.ar.md", __ASTRO_IMAGE_IMPORT_DOR21], ["../flopp2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fhome%2Findex.en.md", __ASTRO_IMAGE_IMPORT_E5BLg], ["../flopp2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fhome%2Findex.it.md", __ASTRO_IMAGE_IMPORT_EmFzh], ["../flopp2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fhome%2Findex.zh.md", __ASTRO_IMAGE_IMPORT_FtgKs], ["./PixelatedGreenTreeSide.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fshowing-off-blog-features%2Findex.en.md", __ASTRO_IMAGE_IMPORT_Z2lmA0V], ["./cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fshowing-off-blog-features%2Findex.en.md", __ASTRO_IMAGE_IMPORT_1mBTjN], ["./PixelatedGreenTreeSide.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fshowing-off-blog-features%2Findex.it.md", __ASTRO_IMAGE_IMPORT_Z2l5wcU], ["./cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fshowing-off-blog-features%2Findex.it.md", __ASTRO_IMAGE_IMPORT_1mSX7O], ["./PixelatedGreenTreeSide.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fshowing-off-blog-features%2Findex.ar.md", __ASTRO_IMAGE_IMPORT_Z2lCkKb], ["./cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fshowing-off-blog-features%2Findex.ar.md", __ASTRO_IMAGE_IMPORT_1mm9zy], ["./PixelatedGreenTreeSide.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fshowing-off-blog-features%2Findex.zh.md", __ASTRO_IMAGE_IMPORT_Z2jXV1J], ["./cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fshowing-off-blog-features%2Findex.zh.md", __ASTRO_IMAGE_IMPORT_1o0yj0]]);
		