
import __ASTRO_IMAGE_IMPORT_Z1tGdvz from "./blog2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fclean-logs-for-agentic-observability%2Findex.ar.md";
import __ASTRO_IMAGE_IMPORT_Z1s2NM8 from "./blog2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fclean-logs-for-agentic-observability%2Findex.zh.md";
import __ASTRO_IMAGE_IMPORT_Z1t9oXj from "./blog2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fclean-logs-for-agentic-observability%2Findex.it.md";
import __ASTRO_IMAGE_IMPORT_Z1tqsLk from "./blog2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fclean-logs-for-agentic-observability%2Findex.en.md";
import __ASTRO_IMAGE_IMPORT_Z2bSEkL from "./blog3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fcodebase-learning-is-agentic-infra%2Findex.ar.md";
import __ASTRO_IMAGE_IMPORT_Z2bCTAw from "./blog3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fcodebase-learning-is-agentic-infra%2Findex.en.md";
import __ASTRO_IMAGE_IMPORT_1erHda from "./blog1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fgive-your-coding-agent-eyes%2Findex.ar.md";
import __ASTRO_IMAGE_IMPORT_Z2blPMv from "./blog3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fcodebase-learning-is-agentic-infra%2Findex.it.md";
import __ASTRO_IMAGE_IMPORT_Z2affBk from "./blog3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fcodebase-learning-is-agentic-infra%2Findex.zh.md";
import __ASTRO_IMAGE_IMPORT_1eHrWp from "./blog1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fgive-your-coding-agent-eyes%2Findex.en.md";
import __ASTRO_IMAGE_IMPORT_DOR21 from "../flopp2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fhome%2Findex.ar.md";
import __ASTRO_IMAGE_IMPORT_E5BLg from "../flopp2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fhome%2Findex.en.md";
import __ASTRO_IMAGE_IMPORT_EmFzh from "../flopp2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fhome%2Findex.it.md";
import __ASTRO_IMAGE_IMPORT_FtgKs from "../flopp2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fhome%2Findex.zh.md";
import __ASTRO_IMAGE_IMPORT_1reFJn from "../avatar.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Faddendum%2Findex.ar.md";
import __ASTRO_IMAGE_IMPORT_1ruqtC from "../avatar.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Faddendum%2Findex.en.md";
import __ASTRO_IMAGE_IMPORT_1sS5sO from "../avatar.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Faddendum%2Findex.zh.md";
import __ASTRO_IMAGE_IMPORT_1rLuhD from "../avatar.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Faddendum%2Findex.it.md";
import __ASTRO_IMAGE_IMPORT_1g66VB from "./blog1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fgive-your-coding-agent-eyes%2Findex.zh.md";
import __ASTRO_IMAGE_IMPORT_1eYvKq from "./blog1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fgive-your-coding-agent-eyes%2Findex.it.md";
export default new Map([["./blog2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fclean-logs-for-agentic-observability%2Findex.ar.md", __ASTRO_IMAGE_IMPORT_Z1tGdvz], ["./blog2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fclean-logs-for-agentic-observability%2Findex.zh.md", __ASTRO_IMAGE_IMPORT_Z1s2NM8], ["./blog2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fclean-logs-for-agentic-observability%2Findex.it.md", __ASTRO_IMAGE_IMPORT_Z1t9oXj], ["./blog2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fclean-logs-for-agentic-observability%2Findex.en.md", __ASTRO_IMAGE_IMPORT_Z1tqsLk], ["./blog3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fcodebase-learning-is-agentic-infra%2Findex.ar.md", __ASTRO_IMAGE_IMPORT_Z2bSEkL], ["./blog3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fcodebase-learning-is-agentic-infra%2Findex.en.md", __ASTRO_IMAGE_IMPORT_Z2bCTAw], ["./blog1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fgive-your-coding-agent-eyes%2Findex.ar.md", __ASTRO_IMAGE_IMPORT_1erHda], ["./blog3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fcodebase-learning-is-agentic-infra%2Findex.it.md", __ASTRO_IMAGE_IMPORT_Z2blPMv], ["./blog3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fcodebase-learning-is-agentic-infra%2Findex.zh.md", __ASTRO_IMAGE_IMPORT_Z2affBk], ["./blog1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fgive-your-coding-agent-eyes%2Findex.en.md", __ASTRO_IMAGE_IMPORT_1eHrWp], ["../flopp2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fhome%2Findex.ar.md", __ASTRO_IMAGE_IMPORT_DOR21], ["../flopp2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fhome%2Findex.en.md", __ASTRO_IMAGE_IMPORT_E5BLg], ["../flopp2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fhome%2Findex.it.md", __ASTRO_IMAGE_IMPORT_EmFzh], ["../flopp2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fhome%2Findex.zh.md", __ASTRO_IMAGE_IMPORT_FtgKs], ["../avatar.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Faddendum%2Findex.ar.md", __ASTRO_IMAGE_IMPORT_1reFJn], ["../avatar.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Faddendum%2Findex.en.md", __ASTRO_IMAGE_IMPORT_1ruqtC], ["../avatar.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Faddendum%2Findex.zh.md", __ASTRO_IMAGE_IMPORT_1sS5sO], ["../avatar.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Faddendum%2Findex.it.md", __ASTRO_IMAGE_IMPORT_1rLuhD], ["./blog1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fgive-your-coding-agent-eyes%2Findex.zh.md", __ASTRO_IMAGE_IMPORT_1g66VB], ["./blog1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fgive-your-coding-agent-eyes%2Findex.it.md", __ASTRO_IMAGE_IMPORT_1eYvKq]]);
		