
import __ASTRO_IMAGE_IMPORT_DOR21 from "../flopp2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fhome%2Findex.ar.md";
import __ASTRO_IMAGE_IMPORT_E5BLg from "../flopp2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fhome%2Findex.en.md";
import __ASTRO_IMAGE_IMPORT_EmFzh from "../flopp2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fhome%2Findex.it.md";
import __ASTRO_IMAGE_IMPORT_FtgKs from "../flopp2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fhome%2Findex.zh.md";
import __ASTRO_IMAGE_IMPORT_1reFJn from "../avatar.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Faddendum%2Findex.ar.md";
import __ASTRO_IMAGE_IMPORT_1ruqtC from "../avatar.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Faddendum%2Findex.en.md";
import __ASTRO_IMAGE_IMPORT_1rLuhD from "../avatar.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Faddendum%2Findex.it.md";
import __ASTRO_IMAGE_IMPORT_1sS5sO from "../avatar.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Faddendum%2Findex.zh.md";
import __ASTRO_IMAGE_IMPORT_1g66VB from "./blog1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fgive-your-coding-agent-eyes%2Findex.zh.md";
import __ASTRO_IMAGE_IMPORT_1eHrWp from "./blog1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fgive-your-coding-agent-eyes%2Findex.en.md";
import __ASTRO_IMAGE_IMPORT_1eYvKq from "./blog1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fgive-your-coding-agent-eyes%2Findex.it.md";
import __ASTRO_IMAGE_IMPORT_1erHda from "./blog1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fgive-your-coding-agent-eyes%2Findex.ar.md";
export default new Map([["../flopp2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fhome%2Findex.ar.md", __ASTRO_IMAGE_IMPORT_DOR21], ["../flopp2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fhome%2Findex.en.md", __ASTRO_IMAGE_IMPORT_E5BLg], ["../flopp2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fhome%2Findex.it.md", __ASTRO_IMAGE_IMPORT_EmFzh], ["../flopp2.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fhome%2Findex.zh.md", __ASTRO_IMAGE_IMPORT_FtgKs], ["../avatar.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Faddendum%2Findex.ar.md", __ASTRO_IMAGE_IMPORT_1reFJn], ["../avatar.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Faddendum%2Findex.en.md", __ASTRO_IMAGE_IMPORT_1ruqtC], ["../avatar.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Faddendum%2Findex.it.md", __ASTRO_IMAGE_IMPORT_1rLuhD], ["../avatar.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Faddendum%2Findex.zh.md", __ASTRO_IMAGE_IMPORT_1sS5sO], ["./blog1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fgive-your-coding-agent-eyes%2Findex.zh.md", __ASTRO_IMAGE_IMPORT_1g66VB], ["./blog1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fgive-your-coding-agent-eyes%2Findex.en.md", __ASTRO_IMAGE_IMPORT_1eHrWp], ["./blog1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fgive-your-coding-agent-eyes%2Findex.it.md", __ASTRO_IMAGE_IMPORT_1eYvKq], ["./blog1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fgive-your-coding-agent-eyes%2Findex.ar.md", __ASTRO_IMAGE_IMPORT_1erHda]]);
		